export const ROLES = {
  ADMIN: 'ADMIN',
  USUARIO: 'USUARIO'
};

export const ROLES_CENTRO = {
  COORDINADOR: 'COORDINADOR',
  PROFESOR: 'PROFESOR',
  ESTUDIANTE: 'ESTUDIANTE',
  OBSERVADOR: 'OBSERVADOR'
};